### ISSUE TITLE
Incompatibility with Mekanism

### ISSUE THREAD

**Issue by KarlosWGeek** [rejahtavi/rfp2#25] opened 2020-02-06 16:10 UTC
**Versions**
Minecraft = 1.12.2
Forge = 14.23.5.2847
RFP2 = 1.12.2-1.2.3

**Does the bug happen when only RFP2 is installed?**
No.

**If the above was NO:**
Please try to narrow down which of your other mods is conflicting. Go through and disable a few at a time and test for the bug in a test world. Which mod(s) seem to be related to the issue?

Mekanism is the conflicting mod.

**Describe the bug**
Mekanism adds five pieces of armor that are not rendered correctly in First and Third Person when RFP2 is installed. Without RFP2 installed, there are no problems, so the mods are incompatible, even though all functions of the armor pieces still work and there are no crashes (only graphical bug).

**How To Reproduce**
Install Forge, Mekanism and RFP2. Enter a test world and wear either the Scuba Mask, Scuba Tank, Jetpack, Armored Jetpack or the Free Runners on their respective armor slots (Helmet, Chestplate or Boots Slot). None of the five will stick to the player's model, they will stay at one position and never move. This issue does not happen without RFP2 installed.

**Expected behavior**
I expected them to stick to the player's model, like any piece of armor does.

**Screenshots**

https://imgur.com/vKimrES
https://imgur.com/tcDpFFo
https://imgur.com/fvVsPTa
https://imgur.com/9GdtX1J
https://imgur.com/auTmKNb

**Comment by rejahtavi** [comment] 2020-02-09 09:00
Thanks for the feedback. I just got back from a pretty long hiatus and am actively developing RFP2 again. A new version will be coming out soon (v1.3.0) that is mainly refactoring and preparing to add more fixes for mod compatibility just like this.

The 1.3.0 release will not have the fix for this in it, but future version might depending on what I find once I look into Mekanism's source and/or contact its developers.

I will update this thread once I have had a chance to look in to it.

Thank you for your patience,

-- Rejah <3

**Comment by rejahtavi** [comment] 2020-02-09 21:45
I have tried, but couldn't reproduce the issue with either 1.2.3 or beta 1.3.2.

It is possible that this is a bug with your version of Mekanism (see if you can update it?) or an interaction with yet another mod other than RFP2 and Mekanism.

Please let me know if updating Mekanism fixes it, and if it doesn't, please send me a copy of your minecraft log file from when this is happening.

Thank you,

-- Rejah <3

**Comment by KarlosWGeek** [comment] 2020-02-09 23:00
I have found out what was causing the issue. It wasn't either Mekanism nor RFP2, but another mod altogether. I installed just Mekanism and RFP2 and it worked. So not really an incompatibility with Mekanism, but an unknown mod from a 64 mods modpack...

**Closed** 2020-03-06 02:44 UTC
Labels: please confirm fix
